### ISSUE TITLE
Having two Voices in two different screen 

### ISSUE THREAD

**Issue by saeid85** [react-native-community/voice#173] opened 2019-04-26 10:21 UTC
Hi,

I need to implement the following scenario:
There are two different TABs in the app (imagine **Tab A** & **Tab B**). each of these tabs have their own *MIC icon* to capture voice and convert it to Text.

When I press for the **first time** on the Mic icon in Tab A, it works fine. Then, I switch to Tab B and press on the Mic icon and it works fine too. **But** when I return to Tab A (for the second time) and press Mic Icon, it triggers the Voice in Tab B!!!

I've tried to use **Voice.stop()** or even **Voice.destroy()** after receiving result in **onSpeechResults** or in **onSpeechEnd** but faced the same issue.

Any idea how I can solve it!?

Thanks.

**Comment by saeid85** [comment] 2019-05-06 02:15
Any idea?

**Comment by shreyasnisal** [comment] 2019-05-06 14:27
Would it be possible for you to share the code here?

**Comment by saeid85** [comment] 2019-05-07 03:31
I just created a test RN app with two Tabs, Then copy&paste example provided by @wenkesj in each Tab.

![tabs](https://user-images.githubusercontent.com/20357845/57268549-c8fea080-70b6-11e9-94a1-df82c7b422b5.png)

I found out even after running the app, if I just go to the Second Tab (without pressing on the Mic Icon) and then return to Home Screen & press On the Mic icon, the result of voice recognition will be displayed in the second tab!!!

Here is the code:

### Home Screen
```javascript
export default class HomeScreen extends Component {
  state = {
    recognized: "",
    pitch: "",
    error: "",
    end: "",
    started: "",
    results: [],
    partialResults: []
  };

  constructor(props) {
    super(props);
    Voice.onSpeechStart = this.onSpeechStart;
    Voice.onSpeechRecognized = this.onSpeechRecognized;
    Voice.onSpeechEnd = this.onSpeechEnd;
    Voice.onSpeechError = this.onSpeechError;
    Voice.onSpeechResults = this.onSpeechResults;
    Voice.onSpeechPartialResults = this.onSpeechPartialResults;
    Voice.onSpeechVolumeChanged = this.onSpeechVolumeChanged;
  }

  componentWillUnmount() {
    Voice.destroy().then(Voice.removeAllListeners);
  }

  onSpeechStart = e => {
    this.setState({ started: "√" });
  };

  onSpeechRecognized = e => {
    this.setState({ recognized: "√" });
  };

  onSpeechEnd = e => {
    this.setState({ end: "√" });
  };

  onSpeechError = e => {
    this.setState({ error: JSON.stringify(e.error) });
  };

  onSpeechResults = e => {
    this.setState({ results: e.value });
  };

  onSpeechPartialResults = e => {
    this.setState({ partialResults: e.value });
  };

  onSpeechVolumeChanged = e => {
    this.setState({ pitch: e.value });
  };

  _startRecognizing = async () => {
    this.setState({
      recognized: "",
      pitch: "",
      error: "",
      started: "",
      results: [],
      partialResults: [],
      end: ""
    });

    try {
      await Voice.start("en-US");
    } catch (e) {
      console.error(e);
    }
  };

  _stopRecognizing = async () => {
    try {
      await Voice.stop();
    } catch (e) {
      console.error(e);
    }
  };

  _cancelRecognizing = async () => {
    try {
      await Voice.cancel();
    } catch (e) {
      console.error(e);
    }
  };

  _destroyRecognizer = async () => {
    try {
      await Voice.destroy();
    } catch (e) {
      console.error(e);
    }
    this.setState({
      recognized: "",
      pitch: "",
      error: "",
      started: "",
      results: [],
      partialResults: [],
      end: ""
    });
  };

  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>Home Screen</Text>
        <Text style={styles.stat}>Results</Text>
        {this.state.results.map((result, index) => {
          return (
            <Text key={`result-${index}`} style={styles.stat}>
              {result}
            </Text>
          );
        })}
        <TouchableHighlight onPress={this._startRecognizing}>
          <MCIcon name="microphone" size={36} style={{ marginTop: 10 }} />
        </TouchableHighlight>
        <TouchableHighlight onPress={this._stopRecognizing}>
          <Text style={styles.action}>Stop Recognizing</Text>
        </TouchableHighlight>
        <TouchableHighlight onPress={this._cancelRecognizing}>
          <Text style={styles.action}>Cancel</Text>
        </TouchableHighlight>
        <TouchableHighlight onPress={this._destroyRecognizer}>
          <Text style={styles.action}>Destroy</Text>
        </TouchableHighlight>
      </View>
    );
  }
}
```

### Products Screen (The Second Tab)
```javascript
export default class ProductsScreen extends Component {
  state = {
    recognized: "",
    pitch: "",
    error: "",
    end: "",
    started: "",
    results: [],
    partialResults: []
  };

  constructor(props) {
    super(props);
    Voice.onSpeechStart = this.onSpeechStart;
    Voice.onSpeechRecognized = this.onSpeechRecognized;
    Voice.onSpeechEnd = this.onSpeechEnd;
    Voice.onSpeechError = this.onSpeechError;
    Voice.onSpeechResults = this.onSpeechResults;
    Voice.onSpeechPartialResults = this.onSpeechPartialResults;
    Voice.onSpeechVolumeChanged = this.onSpeechVolumeChanged;
  }

  componentWillUnmount() {
    Voice.destroy().then(Voice.removeAllListeners);
  }

  onSpeechStart = e => {
    this.setState({ started: "√" });
  };

  onSpeechRecognized = e => {
    this.setState({ recognized: "√" });
  };

  onSpeechEnd = e => {
    this.setState({ end: "√" });
  };

  onSpeechError = e => {
    this.setState({ error: JSON.stringify(e.error) });
  };

  onSpeechResults = e => {
    this.setState({ results: e.value });
  };

  onSpeechPartialResults = e => {
    this.setState({ partialResults: e.value });
  };

  onSpeechVolumeChanged = e => {
    this.setState({ pitch: e.value });
  };

  _startRecognizing = async () => {
    this.setState({
      recognized: "",
      pitch: "",
      error: "",
      started: "",
      results: [],
      partialResults: [],
      end: ""
    });

    try {
      await Voice.start("en-US");
    } catch (e) {
      console.error(e);
    }
  };

  _stopRecognizing = async () => {
    try {
      await Voice.stop();
    } catch (e) {
      console.error(e);
    }
  };

  _cancelRecognizing = async () => {
    try {
      await Voice.cancel();
    } catch (e) {
      console.error(e);
    }
  };

  _destroyRecognizer = async () => {
    try {
      await Voice.destroy();
    } catch (e) {
      console.error(e);
    }
    this.setState({
      recognized: "",
      pitch: "",
      error: "",
      started: "",
      results: [],
      partialResults: [],
      end: ""
    });
  };

  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>Products Screen</Text>
        <Text style={styles.stat}>Results</Text>
        {this.state.results.map((result, index) => {
          return (
            <Text key={`result-${index}`} style={styles.stat}>
              {result}
            </Text>
          );
        })}
        <TouchableHighlight onPress={this._startRecognizing}>
          <MCIcon name="microphone" size={36} style={{ marginTop: 10 }} />
        </TouchableHighlight>
        <TouchableHighlight onPress={this._stopRecognizing}>
          <Text style={styles.action}>Stop Recognizing</Text>
        </TouchableHighlight>
        <TouchableHighlight onPress={this._cancelRecognizing}>
          <Text style={styles.action}>Cancel</Text>
        </TouchableHighlight>
        <TouchableHighlight onPress={this._destroyRecognizer}>
          <Text style={styles.action}>Destroy</Text>
        </TouchableHighlight>
      </View>
    );
  }
}
```

Thanks

**Comment by saeid85** [comment] 2019-05-17 04:27
@wenkesj any idea?

**Comment by Grekain1** [comment] 2019-05-25 09:19
Hello, I have run in the same issue and came up with a solution that works for me. I have two screens A and B where A is the home screen and use a StackNavigator (react-navigation) to navigate between the screens. 

What I have found to be case is that A is initially mounted when the app is loaded and will never unmount even if I navigate to screen B. Screen B will be newly created and mounted every time I navigate to it and unmounted whenever I navigate back to screen A.

As such, in screen B I assign the speech events in the constructor, and destroy them when the component unmounts:

```javascript
// Screen_B
constructor (props) {
    super(props)

    Voice.onSpeechStart = this.onSpeechStart.bind(this)
    Voice.onSpeechRecognized = this.onSpeechRecognized.bind(this)
    Voice.onSpeechEnd = this.onSpeechEnd.bind(this)
    Voice.onSpeechError = this.onSpeechError.bind(this)
    Voice.onSpeechResults = _.debounce(this.onSpeechResults.bind(this), 2000)
    Voice.onSpeechPartialResults = this.onSpeechPartialResults.bind(this)
}

componentWillUnmount () {
    Voice.destroy().then(Voice.removeAllListeners)
}
```

Since screen A does not mount or unmount I cannot use the same method here. I have found that the react-navigation events 'willFocus', 'willBlur', 'didFocus', 'didBlur' were not called correctly and instead used **componentDidUpdate** which is called immediately when returning back to screen A. In order to reduce the load of this method I send a flag from screen B to screen A when navigating back:

```javascript
// Screen_B
this.props.navigation.navigate('Screen_A', {cameBack: true})
```

This flag then determines whether screen A will reassign the event listeners:

```javascript
// Screen_A
componentDidUpdate () {
    if (this.props.navigation.getParam('cameBack', false) === true) {
        this.props.navigation.setParams({
            cameBack: false,
        })
      
        Voice.onSpeechStart = this.onSpeechStart.bind(this)
        Voice.onSpeechRecognized = this.onSpeechRecognized.bind(this)
        Voice.onSpeechEnd = this.onSpeechEnd.bind(this)
        Voice.onSpeechError = this.onSpeechError.bind(this)
        Voice.onSpeechResults = _.debounce(this.onSpeechResults.bind(this), 1000)
        Voice.onSpeechPartialResults = this.onSpeechPartialResults.bind(this)
        Voice.onSpeechVolumeChanged = this.onSpeechVolumeChanged.bind(this)
    }
}
```

The event listeners are also assigned initially in the **componentDidMount** function of screen A. 

I can now switch between screen A and screen B freely and the voice recognition works fine in both. I hope this can help you solve your problem.

**Comment by saeid85** [comment] 2019-05-26 07:41
Hi @Grekain1,
Thanks for the solution. I have not tried it yet but I will try it soon & will update you.

**Comment by lfoliveir4** [comment] 2019-12-16 11:59
> Hi @Grekain1,
> Thanks for the solution. I have not tried it yet but I will try it soon & will update you.

Hello @saeid85 ! Have you tried the solution mentioned above?

**Comment by purna47d** [comment] 2020-03-02 10:42
I tried @Grekain1 solution.
Still, it is not working.

**Comment by Abhijit-Kayande** [comment] 2020-08-13 11:38
I did this and it solved my problem

`Voice.destroy().then(Voice.removeAllListeners);
    Voice.onSpeechStart = this.onSpeechStart.bind(this);
    Voice.onSpeechEnd = this.onSpeechEnd.bind(this);
    Voice.onSpeechRecognized = this.onSpeechRecognized.bind(this);
    Voice.onSpeechResults = this.onSpeechResults.bind(this);`

**Comment by safaiyeh** [comment] 2020-08-14 03:39
Closing as @Abhijit-Kayande confirmed the proposed solution works! Feel free to open another issue if this comes up.

**Closed by safaiyeh** 2020-08-14 03:39 UTC

**Comment by ubaidh** [comment] 2022-03-30 21:33
> Closing as @Abhijit-Kayande confirmed the proposed solution works! Feel free to open another issue if this comes up.

nope doesn't work for me

**Comment by CanamSystems** [comment] 2022-05-10 17:34
Hi @ubaidh, I managed to resolve the issue just by attaching the event listeners on the show mic button. Do not attach them on the useEffect({}, [])  or componentDidMount().

**Comment by ubaidh** [comment] 2022-06-12 10:17
> Hi @ubaidh, I managed to resolve the issue just by attaching the event listeners on the show mic button. Do not attach them on the useEffect({}, []) or componentDidMount().

this did work thank you

**Comment by rohankm** [comment] 2023-02-22 11:47
> Hi @ubaidh, I managed to resolve the issue just by attaching the event listeners on the show mic button. Do not attach them on the useEffect({}, []) or componentDidMount().

can you share the code please?

**Comment by humblesami** [comment] 2023-10-07 07:06
There is another working solution (two voice controls in same tab) here
https://stackoverflow.com/questions/77244219/using-multiple-instances-of-a-library-that-returns-an-instance/77248741#answer-77248741
