### ISSUE TITLE
Handlers (onSpeechStart,  onSpeechResults) called twice on Android

### ISSUE THREAD

**Issue by mbody** [react-native-community/voice#246] opened 2020-04-01 19:41 UTC
When running the example provided (VoiceTest)  in a new project (RN 0.61.5) I have handlers called twice and the sounds of sarting/detection seems playing twice also...

**Comment by mbody** [comment] 2020-04-01 20:04
Seems related to https://stackoverflow.com/questions/60853257/android-recognitionlistener-onresults-being-called-twice

**Comment by luketowell** [comment] 2020-04-24 15:22
This has also just recently started happening in one of my applications. 

I can see that the startVoiceRecognition is called once however for some reason the onSpeechResults handler is being triggered twice.

I've provided the code snippets below and the output from my console to quickly debug the issue:
```
constructor(props) {
        super(props);
        Voice.onSpeechResults = this.onSpeechResults.bind(this);
    }

onSpeechResults = e => {
        console.log("called")
        // this then goes off and updates conversations and sends text to other services. 
        this.props.sendMessage(e.value[0]);
};

 startVoiceRecognition = async () => {
        console.log("start voice recognition called")
        try {
            await Voice.start('en-GB');
        } catch (e) {
            console.error(e);
        }
    } 
```

Console output:
![image](https://user-images.githubusercontent.com/29888913/80228946-9f33e600-8647-11ea-86ce-eaffc812b746.png)

(Notice how "start voice recognition called" is called once and then the onSpeechResults prints "called" out twice)

Has anyone made any progress on this?

**Comment by Brokray** [comment] 2020-04-30 13:12
I have the same issue, I search a little bit and found informations about it. It seems to be related to the Google API itself and the issue is already tracked by Google 
 (https://issuetracker.google.com/issues/152628934).

To avoid this caveat I simply added a debounce on my event caller, like that :
```javascript
 Voice.onSpeechResults = debounce(({ value }): void => {
    doMaThing();
  }, 50);
```

I hope this can help you for the moment.

**Comment by teofiloribeiro** [comment] 2020-05-12 22:58
Same problem here! :/

**Comment by oswalgopal** [comment] 2020-07-22 17:36
ya even I faced the same issue with my app but I fixed it with a custom logic that is using a flag means a variable let it be a temp variable and by default set it as a false.

what you need to do set the temp as true wherever you are starting listening voice. Then in your handler what you need to do is just add a if condition on the basis of temp variable like

if (temp) { do something temp = false }

so what will happen you handler will be called twice as usual but you will be able to handle this data only.

**Comment by safaiyeh** [comment] 2020-07-24 02:28
> I had the same issue.
> It seems to be related to the Google API itself and the issue is already tracked by Google: https://issuetracker.google.com/issues/152628934.
> 
> To avoid this caveat I simply added a debounce on my event caller, like that :
> 
> ```js
>  Voice.onSpeechResults = debounce(({ value }): void => {
>     doMaThing();
>   }, 50);
> ```
> 
> I hope this can help you for the moment.

@mbody does this help you? Since this a Google API issue, no action can be taken from this repo. Should we add a mention of this in the docs?

**Comment by teofiloribeiro** [comment] 2020-07-24 03:07
Guys as @Brokray said this issue is tracked by google here https://issuetracker.google.com/issues/152628934, they change the status to fixed couple days ago, I did a test here, everything is working well now

**Comment by safaiyeh** [comment] 2020-07-24 04:31
Thanks @teofiloribeiro ill close the issue now

**Closed by safaiyeh** 2020-07-24 04:31 UTC
